# Generated by Django 4.1.2 on 2022-10-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptesespece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreation', models.DateTimeField(blank=True, db_column='DateCreation', null=True)),
                ('web', models.CharField(blank=True, db_column='Web', max_length=255, null=True)),
                ('etat', models.CharField(blank=True, db_column='Etat', max_length=255, null=True)),
                ('idclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imputationsespeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(blank=True, db_column='Montant', null=True)),
                ('sens', models.IntegerField(blank=True, db_column='Sens', null=True)),
                ('dateimputation', models.DateTimeField(blank=True, db_column='DateImputation', null=True)),
                ('iddateimputation', models.IntegerField(blank=True, db_column='IdDateImputation', null=True)),
                ('datevaleur', models.DateTimeField(blank=True, db_column='DateValeur', null=True)),
                ('nature', models.CharField(blank=True, db_column='Nature', max_length=255, null=True)),
                ('etat', models.IntegerField(blank=True, db_column='Etat', null=True)),
                ('dateetat', models.DateTimeField(auto_now_add=True)),
                ('libelle', models.TextField(blank=True, max_length=255, null=True)),
                ('idcompteespece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.comptesespece')),
            ],
        ),
    ]
