# Generated by Django 4.1.2 on 2022-10-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imputationsespeces',
            options={'permissions': [('control_clients', 'Can detect sespect clients')]},
        ),
    ]
